apiVersion: logging.openshift.io/v1
kind: ClusterLogging
metadata:
  name: instance 
  namespace: openshift-logging 
spec:
  collection:
    type: vector
  logStore:
    lokistack:
      name: logging-loki
  visualization:
    type: ocp-console  
    # nodeSelector:
    #   node-role.kubernetes.io/infra: ''
  managementState: Managed
